sudo: required
services:
    - docker

before_install:
    - docker build -t chintandocker/react-test -f ./client/Dockerfile.dev .

script:
    - docker run -e CI=true chintandocker/react-test npm test

after_success:
    - docker build -t chintandocker/multi-client ./client
    - docker build -t chintandocker/multi-nginx ./nginx
    - docker build -t chintandocker/multi-server ./server
    - docker build -t chintandocker/multi-worker ./worker